name: Monitor de Jogos 24/7

on:
  schedule:
    - cron: '*/10 * * * *'  # Executa a cada 10 minutos
  workflow_dispatch:  # Permite executar manualmente

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar dependências
        run: pip install -r requirements.txt
      - name: Executar monitor
        run: python monitor.py
